[tasks."prove"]
dependencies = [
  "build:circuit",
  "build:setup",
  "build:proof",
  "build:values",
]

[tasks."build:circuit"]
script = '''
cd circuit
circom main.circom --r1cs --wasm
'''

[tasks."build:setup"]
script = '''
# セットアップの初期フェーズを開始し、新しいPowers of Tauファイルを生成します。
cd trusted_setup

# bn128カーブを使用して、12の次数のPowers of Tauセレモニーを開始します。
snarkjs powersoftau new bn128 12 pot12_0000.ptau -v

# 既存のPowers of Tauファイルに寄与を追加して新しいファイルを生成します。
snarkjs powersoftau contribute pot12_0000.ptau pot12_0001.ptau --name="First contribution" -v

# Phase 2の準備のためにPowers of Tauファイルを変換します。
snarkjs powersoftau prepare phase2 pot12_0001.ptau pot12_final.ptau -v

# R1CS制約ファイルとPowers of Tauファイルを使用して、新しいzkeyファイルを生成します。
snarkjs zkey new ../circuit/main.r1cs pot12_final.ptau circuit_0000.zkey

# 既存のzkeyファイルに寄与を追加して新しいzkeyファイルを生成します。
snarkjs zkey contribute circuit_0000.zkey circuit_0001.zkey --name="First contribution" -v

# zkeyファイルから検証キーをエクスポートしてJSONファイルに保存します。
snarkjs zkey export verificationkey circuit_0001.zkey verification_key.json
'''

[tasks."build:proof"]
script = '''
cd prover
# ウィットネスの計算
snarkjs wtns calculate ../circuit/main_js/main.wasm input.json witness.wtns

# groth16の証明の生成
snarkjs groth16 prove ../trusted_setup/circuit_0001.zkey witness.wtns proof.json public.json
'''

[tasks."build:values"]
script = '''
cd utils
cargo run
'''
